export const catsVdogs = [
  {
    slideNumber: 0,
    title: "Are Cats Better than Dogs?",
    subTitle: "A Tale of Absurdity",
  },
  {
    slideNumber: 1,
    title: "Purr vs. Woof",
    subTitle: "An Analysis of Sound Effects",
    copy: "Cats purr because they are secretly plotting world domination. Dogs woof to communicate with aliens.",
    imgPrompt: "cats and dogs arguing",
    img: "/imgs/catsVdogs-1.png",
    imgName: "catsVdogs-1",
  },
  {
    slideNumber: 2,
    title: "Meow-o-meter vs. Bark-o-graph",
    subTitle: "Tracking the Sound Waves",
    copy: "According to the Meow-o-meter, cats' meows have a frequency specifically designed to annoy humans. Bark-o-graph measures the volume of dog barks in relation to the global noise pollution.",
    imgPrompt: "meow-o-meter and bark-o-graph",
    img: "/imgs/catsVdogs-2.png",
    imgName: "catsVdogs-2",
  },
  {
    slideNumber: 3,
    title: "Hierarchy of Needs",
    subTitle: "Food, Sleep, and World Domination",
    copy: "Cats prioritize food, sleep, and world domination in that order. Dogs prioritize world domination, food, and sleep in that order.",
    imgPrompt: "hierarchy of needs for cats and dogs",
    img: "/imgs/catsVdogs-3.png",
    imgName: "catsVdogs-3",
  },
  {
    slideNumber: 4,
    title: "True Happiness",
    subTitle: "Quantifying the Joy",
    copy: "Studies show that cats achieve true happiness when they can fit inside the smallest boxes. Dogs achieve true happiness when they can catch their own tails.",
    imgPrompt: "cats fitting in small boxes and dogs chasing their tails",
    img: "/imgs/catsVdogs-4.png",
    imgName: "catsVdogs-4",
  },
  {
    slideNumber: 5,
    title: "Intelligence Quotient",
    subTitle: "Einstein-level Cuteness",
    copy: "Cats have an IQ that is off the charts but only when it comes to opening doors for themselves. Dogs have the amazing ability to understand and interpret human facial expressions.",
    imgPrompt: "cats opening doors and dogs understanding human faces",
    img: "/imgs/catsVdogs-5.png",
    imgName: "catsVdogs-5",
  },
  {
    slideNumber: 6,
    title: "Language Mastery",
    subTitle: "Meow or Woof-ese?",
    copy: "Cats have mastered the art of meowing in different accents, dialects, and even foreign languages. Dogs can bark fluently in Morse code.",
    imgPrompt:
      "cats meowing in different accents and dogs barking in Morse code",
    img: "/imgs/catsVdogs-6.png",
    imgName: "catsVdogs-6",
  },
  {
    slideNumber: 7,
    title: "Treat Affection Ratio",
    subTitle: "The Path to Love",
    copy: "For every ten treats given, a cat will consider showing affection once. A dog's love is unconditional and can be earned with a single treat.",
    imgPrompt: "cats receiving treats and dogs offering unconditional love",
    img: "/imgs/catsVdogs-7.png",
    imgName: "catsVdogs-7",
  },
  {
    slideNumber: 8,
    title: "Napping Patterns",
    subTitle: "The Art of Snoozing",
    copy: "Cats have mastered the complicated logic behind strategically choosing the most inconvenient places to take naps. Dogs have a natural talent for finding the comfiest spots in the room.",
    imgPrompt:
      "cats napping in peculiar places and dogs sleeping on cozy blankets",
    img: "/imgs/catsVdogs-8.png",
    imgName: "catsVdogs-8",
  },
  {
    slideNumber: 9,
    title: "Final Verdict",
    subTitle: "The Ultimate Showdown",
    copy: "In a battle of superiority, the cats would distract their opponents with lasers while the dogs would charm them with their irresistible puppy eyes.",
    imgPrompt: "cats shooting lasers and dogs with puppy eyes",
    img: "/imgs/catsVdogs-9.png",
    imgName: "catsVdogs-9",
  },
];
