export const hollowMoon = [
  {
    slideNumber: 0,
    title: "The Hollow Moon Chronicles",
    subTitle: "An Absurd Journey into Lunacy",
  },
  {
    slideNumber: 1,
    title: "Introduction",
    subTitle: "Welcome to the Wacky World Below",
    copy: "On the hidden side of the moon, a secret society of moon people enjoys a life full of belly laughs and intergalactic tomfoolery.",
    imgPrompt: "Moon people",
    img: "/imgs/hollowMoon-1.png",
    imgName: "hollowMoon-1",
  },
  {
    slideNumber: 2,
    title: "Lunar Laughs",
    subTitle: "Harnessing the Power of Joviality",
    copy: "Moon dwellers are born with a natural ability to generate laughter, making their silly society thrive amidst endless punchlines.",
    imgPrompt: "Laughing moon",
    img: "/imgs/hollowMoon-2.png",
    imgName: "hollowMoon-2",
  },
  {
    slideNumber: 3,
    title: "Silly Stats",
    subTitle: "Quantifying the Absurd",
    copy: "Chart depicting the correlation between moon phases and the prevalence of lunar humor. Full moon = highest giggle intensity!",
    imgPrompt: "Moon phases and humor",
    img: "/imgs/hollowMoon-3.png",
    imgName: "hollowMoon-3",
  },
  {
    slideNumber: 4,
    title: "Belly Laugh Bell Curve",
    subTitle: "Analyzing Guffaw Distribution",
    copy: "The hilarious distribution of laughter among moon citizens follows a bell curve, with the most boisterous bursts at the peak!",
    imgPrompt: "Bell curve of laughter",
    img: "/imgs/hollowMoon-4.png",
    imgName: "hollowMoon-4",
  },
  {
    slideNumber: 5,
    title: "Mirthful Mind Map",
    subTitle: "Navigating the Lunar Lunacy",
    copy: "A complex mind map delving into the intricate web of interconnected jokes, puns, and comical threads that form the backbone of lunar humor.",
    imgPrompt: "Mind map of lunar humor",
    img: "/imgs/hollowMoon-5.png",
    imgName: "hollowMoon-5",
  },
  {
    slideNumber: 6,
    title: "Infinite Silliness Loop",
    subTitle: "When a Joke Keeps Going",
    copy: "A step-by-step diagram illustrating the bizarre phenomenon of infinite silliness loops, where a single joke can generate laughter eternally.",
    imgPrompt: "Infinite loop of laughter",
    img: "/imgs/hollowMoon-6.png",
    imgName: "hollowMoon-6",
  },
  {
    slideNumber: 7,
    title: "Insider Jargon",
    subTitle: "Cracking the Lunar Lexicon",
    copy: "Unveiling the cryptic language of moon humor, peppered with hilarious acronyms and made-up words that leave Earthlings puzzled.",
    imgPrompt: "Moon language",
    img: "/imgs/hollowMoon-7.png",
    imgName: "hollowMoon-7",
  },
  {
    slideNumber: 8,
    title: "Lunatic Lifestyle",
    subTitle: "Day-to-Day Absurdities",
    copy: "An info bubble highlighting the zany daily routines followed by moon dwellers, where accidentally wearing clown shoes is considered a fashion statement.",
    imgPrompt: "Daily absurdities on the moon",
    img: "/imgs/hollowMoon-8.png",
    imgName: "hollowMoon-8",
  },
  {
    slideNumber: 9,
    title: "Conclusion",
    subTitle: "Embrace the Absurd",
    copy: "Remember, life is more fun when you let your inner moon person shine and embrace the delightful lunacy that surrounds us all!",
    imgPrompt: "Embrace the absurd",
    img: "/imgs/hollowMoon-9.png",
    imgName: "hollowMoon-9",
  },
];
