export const hotdogEarth = [
  {
    slideNumber: 0,
    title: "The Earth Isn't Flat",
    subTitle: "It's Hotdog Shaped",
  },
  {
    slideNumber: 1,
    title: "The Hotdog Hypothesis",
    subTitle: "Unveiling the Truth",
    copy: "The hotdog shape theory suggests that our Earth is not round, but hotdog-shaped!",
    imgPrompt: "Hotdog-shaped Earth",
    img: "/imgs/hotdogEarth-1.png",
    imgName: "hotdogEarth-1",
  },
  {
    slideNumber: 2,
    title: "Hotdogs per Latitude",
    subTitle: "Hotdog Density Chart",
    copy: "Using cutting-edge technology, we measured the number of hotdogs per latitude.",
    imgPrompt: "Hotdog Density Chart",
    img: "/imgs/hotdogEarth-2.png",
    imgName: "hotdogEarth-2",
  },
  {
    slideNumber: 3,
    title: "The Sausage-Sun Connection",
    subTitle: "Solar Grill Theory",
    copy: "According to the solar grill theory, the Sun's rays perfectly cook hotdogs on Earth's surface.",
    imgPrompt: "Sausage-Sun Connection",
    img: "/imgs/hotdogEarth-3.png",
    imgName: "hotdogEarth-3",
  },
  {
    slideNumber: 4,
    title: "Hotdog Bell Curve",
    subTitle: "Distribution of Hotdogs",
    copy: "Analyzing hotdog consumption across continents, we discovered a fascinating bell curve.",
    imgPrompt: "Hotdog Bell Curve",
    img: "/imgs/hotdogEarth-4.png",
    imgName: "hotdogEarth-4",
  },
  {
    slideNumber: 5,
    title: "Hotdogs vs. Hamburger",
    subTitle: "The Great Food Battle",
    copy: "In the epic battle of hotdogs vs. hamburgers, hotdogs clearly triumph as the Earth's iconic shape.",
    imgPrompt: "Hotdogs vs. Hamburgers",
    img: "/imgs/hotdogEarth-5.png",
    imgName: "hotdogEarth-5",
  },
  {
    slideNumber: 6,
    title: "Flowchart of Hotdog Logic",
    subTitle: "The Inner Workings",
    copy: "The intricate flow of hotdog logic unraveled through rigorous analysis, defying all flat Earth theories.",
    imgPrompt: "Flowchart of Hotdog Logic",
    img: "/imgs/hotdogEarth-6.png",
    imgName: "hotdogEarth-6",
  },
  {
    slideNumber: 7,
    title: "Hotdog Insider Jargon",
    subTitle: "Learning the Lingo",
    copy: "Delve into the fascinating world of hotdogs with our guide to insider jargon and fake words.",
    imgPrompt: "Hotdog Insider Jargon",
    img: "/imgs/hotdogEarth-7.png",
    imgName: "hotdogEarth-7",
  },
  {
    slideNumber: 8,
    title: "The H.O.T.D.O.G. System",
    subTitle: "Hotdog Oriented Tracking",
    copy: "Our cutting-edge H.O.T.D.O.G. system uses advanced technology to track hotdog-related phenomena.",
    imgPrompt: "The H.O.T.D.O.G. System",
    img: "/imgs/hotdogEarth-8.png",
    imgName: "hotdogEarth-8",
  },
  {
    slideNumber: 9,
    title: "Hotdogs of the World",
    subTitle: "Cultural Hotdog Diversity",
    copy: "Explore the rich variety of hotdogs around the world, from the mind-boggling Kimchi Dog to the extravagant Truffle Dog.",
    imgPrompt: "Hotdogs of the World",
    img: "/imgs/hotdogEarth-9.png",
    imgName: "hotdogEarth-9",
  },
  {
    slideNumber: 10,
    title: "Conclusion",
    subTitle: "Embrace the Hotdog Truth",
    copy: "In conclusion, the hotdog-shaped Earth theory is a paradigm-shifting revelation that will forever change our understanding of the world.",
    imgPrompt: "Hotdog Truth",
    img: "/imgs/hotdogEarth-10.png",
    imgName: "hotdogEarth-10",
  },
];
