import { Deck } from ".";

export const iPhoneVAndroid: Deck = [
  {
    slideNumber: 0,
    title: "Are iPhones Better Than Androids?",
    subTitle: "A Silly Presentation",
  },
  {
    slideNumber: 1,
    title: "The Battle Begins",
    subTitle: "Epic Showdown",
    copy: "iPhones and Androids clash in a pixelated arena!",
    imgPrompt: "Phone fight",
    img: "/imgs/iPhoneVAndroid-1.png",
    imgName: "iPhoneVAndroid-1",
  },
  {
    slideNumber: 2,
    title: "The Power of i",
    subTitle: "iPhones vs. Androids",
    copy: "Who will harness the mystical power of 'i'?",
    imgPrompt: "Mystical 'i'",
    img: "/imgs/iPhoneVAndroid-2.png",
    imgName: "iPhoneVAndroid-2",
  },
  {
    slideNumber: 3,
    title: "The Emoji War",
    subTitle: "Revealing the True Battle",
    copy: "Discover how emojis are the ultimate weapon in this rivalry!",
    imgPrompt: "Emoji showdown",
    img: "/imgs/iPhoneVAndroid-3.png",
    imgName: "iPhoneVAndroid-3",
  },
  {
    slideNumber: 4,
    title: "The Curious Case of Applesauce",
    subTitle: "A Delicious Investigation",
    copy: "Uncover the secret Apple sauce behind iPhones' success!",
    imgPrompt: "Apple sauce mystery",
    img: "/imgs/iPhoneVAndroid-4.png",
    imgName: "iPhoneVAndroid-4",
  },
  {
    slideNumber: 5,
    title: "Brain Over Brawn",
    subTitle: "Exploring Intellectual Superiority",
    copy: "Witness the intellectual prowess of iPhones and Androids' brainiacs!",
    imgPrompt: "Brain vs. Muscle",
    img: "/imgs/iPhoneVAndroid-5.png",
    imgName: "iPhoneVAndroid-5",
  },
  {
    slideNumber: 6,
    title: "The Great Teardown",
    subTitle: "Unmasking the Inner Secrets",
    copy: "Dive into the abyss of motherboard madness!",
    imgPrompt: "Teardown frenzy",
    img: "/imgs/iPhoneVAndroid-6.png",
    imgName: "iPhoneVAndroid-6",
  },
  {
    slideNumber: 7,
    title: "The Zerogram Paradox",
    subTitle: "Quantum Buzzwords Decoded",
    copy: "Demystify the groundbreaking concept of the elusive Zerogram!",
    imgPrompt: "Zerogram revelation",
    img: "/imgs/iPhoneVAndroid-7.png",
    imgName: "iPhoneVAndroid-7",
  },
  {
    slideNumber: 8,
    title: "The Compelling Force",
    subTitle: "And the Winner Is...",
    copy: "Discover the irresistible force that drives iPhones to the top!",
    imgPrompt: "Irresistible force",
    img: "/imgs/iPhoneVAndroid-8.png",
    imgName: "iPhoneVAndroid-8",
  },
  {
    slideNumber: 9,
    title: "The Legend Continues",
    subTitle: "Eternal Rivalry",
    copy: "The battle between iPhones and Androids shall forever echo in the halls of technology!",
    imgPrompt: "Eternal rivalry",
    img: "/imgs/iPhoneVAndroid-9.png",
    imgName: "iPhoneVAndroid-9",
  },
  {
    slideNumber: 10,
    title: "And the Answer Is...",
    subTitle: "No One Knows!",
    copy: "After all, it's just a fun and absurd debate!",
    imgPrompt: "The question mark",
    img: "/imgs/iPhoneVAndroid-10.png",
    imgName: "iPhoneVAndroid-10",
  },
];
