export const PizzaHelpDesk = [
  {
    slideNumber: 0,
    title: "A Business Plan for a Pizza Help Desk",
    subTitle: "Making Pizza Problems a Piece of Cake",
  },
  {
    slideNumber: 1,
    title: "Introduction",
    subTitle: "Revolutionizing Pizza Crisis Management",
    copy: "In this fast-paced world of melted cheese emergencies, we bring you the ultimate solution!",
    imgPrompt: "Cheese explosion",
    img: "/imgs/PizzaHelpDesk-1.png",
    imgName: "PizzaHelpDesk-1",
  },
  {
    slideNumber: 2,
    title: "Market Analysis",
    subTitle: "Pepperoni Prospects and Margherita Metrics",
    copy: "Our intricate chart showcases the correlation between pizza cravings and customer satisfaction, leaving no room for doubt.",
    imgPrompt: "Pizza cravings vs. customer satisfaction",
    img: "/imgs/PizzaHelpDesk-2.png",
    imgName: "PizzaHelpDesk-2",
  },
  {
    slideNumber: 3,
    title: "Revenue Projection",
    subTitle: "Doughnut Holes and Pizza Pockets",
    copy: "Our groundbreaking formula unveils the potential profits from offering round-the-clock pizza assistance.",
    imgPrompt: "Piles of money topped with pizzas",
    img: "/imgs/PizzaHelpDesk-3.png",
    imgName: "PizzaHelpDesk-3",
  },
  {
    slideNumber: 4,
    title: "Operations Plan",
    subTitle: "From Dough to Deliveries",
    copy: "Navigate through our elaborate flowchart to witness the miraculous transformation of pizza crises into steaming boxes of relief.",
    imgPrompt: "Flowchart of pizza crisis management",
    img: "/imgs/PizzaHelpDesk-4.png",
    imgName: "PizzaHelpDesk-4",
  },
  {
    slideNumber: 5,
    title: "Technical Infrastructure",
    subTitle: "Jalapenos and Digital Jalometrices",
    copy: "Through the complex intertwining of spicy technology and cheesy innovation, we create a digital ecosystem of pizza repair.",
    imgPrompt: "Digital ecosystem of pizza repair",
    img: "/imgs/PizzaHelpDesk-5.png",
    imgName: "PizzaHelpDesk-5",
  },
  {
    slideNumber: 6,
    title: "Customer Support",
    subTitle: "From Crust Cracking to Sauce Soothing",
    copy: "Our helpline agents, armed with secret dough recipes and gooey puns, are ready 24/7 to tackle all 'topping over' troubles.",
    imgPrompt: "Customer support heroes with pizza capes",
    img: "/imgs/PizzaHelpDesk-6.png",
    imgName: "PizzaHelpDesk-6",
  },
  {
    slideNumber: 7,
    title: "Marketing Strategy",
    subTitle: "Slices and Tactics",
    copy: "With our out-of-the-pizza-box marketing strategies, we'll spread the word about 'Help-a-Pizza' faster than molten cheese melts!",
    imgPrompt: "A pizza-shaped billboard towering over a city",
    img: "/imgs/PizzaHelpDesk-7.png",
    imgName: "PizzaHelpDesk-7",
  },
  {
    slideNumber: 8,
    title: "Investment Opportunities",
    subTitle: "Croutons and Sausage Swirls",
    copy: "Become a doughnator and invest in our pizza rescue mission. Together, we'll conquer the culinary cosmos!",
    imgPrompt: "A pizza rocket launching into space",
    img: "/imgs/PizzaHelpDesk-8.png",
    imgName: "PizzaHelpDesk-8",
  },
  {
    slideNumber: 9,
    title: "Conclusion",
    subTitle: "Feeding Hearts, One Slice at a Time",
    copy: "In the realm of pizza disasters, our help desk is the guardian angel, ensuring pizzas are enjoyed without a hitch!",
    imgPrompt: "An angelic pizza descending from the heavens",
    img: "/imgs/PizzaHelpDesk-9.png",
    imgName: "PizzaHelpDesk-9",
  },
];
