export const poolWater = [
  {
    slideNumber: 0,
    title: "The Untapped Market",
    subTitle: "Bottled Chlorinated Pool Water",
  },
  {
    slideNumber: 1,
    title: "Dive into Profit",
    subTitle: "Making Waves in the Beverage Industry",
    copy: "Introducing Splash-O, the revolutionary bottled chlorinated pool water that will have you drowning in profits!",
    imgPrompt: "a bottle of water with a pool as the label",
    img: "/imgs/poolWater-1.png",
    imgName: "poolWater-1",
  },
  {
    slideNumber: 2,
    title: "Diving Deep",
    subTitle: "Exploring the Demand",
    copy: "Our market research shows an unprecedented demand for chlorinated pool water as a refreshing and nostalgic drink option.",
    imgPrompt: "a graph showing an exponential increase in demand",
    img: "/imgs/poolWater-2.png",
    imgName: "poolWater-2",
  },
  {
    slideNumber: 3,
    title: "Pool Water Popularity",
    subTitle: "Charting the Trend",
    copy: "According to our extensive surveys, 9 out of 10 people secretly crave the taste of chlorine while sipping their beverages.",
    imgPrompt:
      "a chart with labeled categories: 'Water', 'Soda', 'Juice', and 'Pool Water' with 'Pool Water' being the highest",
    img: "/imgs/poolWater-3.png",
    imgName: "poolWater-3",
  },
  {
    slideNumber: 4,
    title: "Making Waves in Sales",
    subTitle: "Riding the Chlorinated Wave",
    copy: "Our sales figures have surged like a perfect cannonball, propelling Splash-O to become the most sought-after drink in the market.",
    imgPrompt: "a diagram depicting a wave with a Splash-O bottle riding it",
    img: "/imgs/poolWater-4.png",
    imgName: "poolWater-4",
  },
  {
    slideNumber: 5,
    title: "Pool Water Logic",
    subTitle: "Cracking the Aqua Code",
    copy: "Our scientists have unraveled the complex chemistry of pool water, extracting the essence of summer and happiness in every sip.",
    imgPrompt:
      "a diagram of complicated logic with arrows, symbols, and equations",
    img: "/imgs/poolWater-5.png",
    imgName: "poolWater-5",
  },
  {
    slideNumber: 6,
    title: "Jargon Bubbles",
    subTitle: "Understanding Our Lingo",
    copy: "We sprinkle phrases like 'Hydro-Happiness' and 'Aqua-Zest' to ensure customers feel the true essence of our pool water.",
    imgPrompt:
      "a thought bubble with random words like 'Hydro-Happiness', 'Diving Delight', and 'Aqua-Zest'",
    img: "/imgs/poolWater-6.png",
    imgName: "poolWater-6",
  },
  {
    slideNumber: 7,
    title: "A.C.E. Formula",
    subTitle: "Achieving Chlorinated Excellence",
    copy: "Our secret recipe follows the A.C.E. formula: Aqua Solution, Chlorine Innovation, Exquisite Bottling.",
    imgPrompt:
      "a diagram with 'A.C.E. Formula' at the center, surrounded by arrows pointing to 'Aqua Solution', 'Chlorine Innovation', and 'Exquisite Bottling'",
    img: "/imgs/poolWater-7.png",
    imgName: "poolWater-7",
  },
  {
    slideNumber: 8,
    title: "Pool Water Bell Curve",
    subTitle: "Riding the Chlorinated Peak",
    copy: "The demand for Splash-O follows a bell curve, with peak sales during summer and a devoted cult following that defies all logical explanations.",
    imgPrompt:
      "a bell curve with 'Sales' on the y-axis and 'Time' on the x-axis, showing a peak during summer months",
    img: "/imgs/poolWater-8.png",
    imgName: "poolWater-8",
  },
  {
    slideNumber: 9,
    title: "Synchronized Refreshment",
    subTitle: "Join the Splashlympics!",
    copy: "Splash-O is the official drink of synchronized swimming teams worldwide, ensuring perfect hydration and aquatic elegance.",
    imgPrompt:
      "an image of a synchronized swimming team having a toast with Splash-O bottles",
    img: "/imgs/poolWater-9.png",
    imgName: "poolWater-9",
  },
  {
    slideNumber: 10,
    title: "Dive into Success",
    subTitle: "Chlorinated Dreams Await",
    copy: "Invest in Splash-O today and dive headfirst into a profitable and utterly absurd adventure!",
    imgPrompt: "a businessman diving into a pool filled with Splash-O bottles",
    img: "/imgs/poolWater-10.png",
    imgName: "poolWater-10",
  },
];
