export const secondhandToothbrushes = [
  {
    slideNumber: 0,
    title: "Innovations in Secondhand toothbrushes:",
    subTitle: "Now with Cheese Flavor",
  },
  {
    slideNumber: 1,
    title: "Revolutionizing Oral Hygiene",
    subTitle: "Introducing Cheese-Fueled Dentistry",
    copy: "Experience the mind-blowing sensation of brushing your teeth with a secondhand toothbrush infused with the savory taste of cheese! It's like a cheese tasting party for your mouth!",
    imgPrompt: "A toothbrush covered in melted cheese",
    img: "/imgs/secondhandToothbrushes-1.png",
    imgName: "secondhandToothbrushes-1",
  },
  {
    slideNumber: 2,
    title: "Why Secondhand?",
    subTitle: "The Recycled Dental Movement",
    copy: "Save the planet one toothbrush at a time! Our secondhand toothbrushes are sourced from dentists, celebrities, and even toothbrush collectors. Join the eco-friendly toothbrush revolution today!",
    imgPrompt: "A toothbrush wearing a recycling symbol",
    img: "/imgs/secondhandToothbrushes-2.png",
    imgName: "secondhandToothbrushes-2",
  },
  {
    slideNumber: 3,
    title: "Cheese Flavor Amplification",
    subTitle: "The Science of Cheesy Teeth",
    copy: "Through cutting-edge technology, we have managed to encapsulate the essence of various cheese flavors in microscopic form, ensuring that every bristle carries the cheesy goodness to your teeth. Say cheese!",
    imgPrompt: "A dental diagram with arrows pointing to cheese molecules",
    img: "/imgs/secondhandToothbrushes-3.png",
    imgName: "secondhandToothbrushes-3",
  },
  {
    slideNumber: 4,
    title: "The Cheese Brushing Experience",
    subTitle: "Embrace the Dairyliciousness",
    copy: "Prepare for a delightful sensory journey as you brush away plaque with our cheese-flavored toothbrush. It's like having a mini fondue party in your mouth, but without the mess!",
    imgPrompt: "A person brushing their teeth with a giant cheese wedge",
    img: "/imgs/secondhandToothbrushes-4.png",
    imgName: "secondhandToothbrushes-4",
  },
  {
    slideNumber: 5,
    title: "Customer Satisfaction",
    subTitle: "Hear It from Our Cheesified Customers",
    copy: "Our devoted customers can't stop raving about the incredible cheese-flavored brushing experience! Join them in achieving a smile that's both cheesier and whiter.",
    imgPrompt: "A speech bubble with the words 'I love my cheesy teeth!'",
    img: "/imgs/secondhandToothbrushes-5.png",
    imgName: "secondhandToothbrushes-5",
  },
  {
    slideNumber: 6,
    title: "Cheese Flavor Spectrum",
    subTitle: "From Mild to Extra Sharp",
    copy: "Discover the diverse range of cheese flavors we have masterfully infused into our toothbrushes. Whether you prefer a subtle cheddar or a tangy blue cheese, we have a toothbrush to satisfy your cheesy cravings!",
    imgPrompt:
      "A chart with different cheese types and their corresponding toothbrush flavors",
    img: "/imgs/secondhandToothbrushes-6.png",
    imgName: "secondhandToothbrushes-6",
  },
  {
    slideNumber: 7,
    title: "Research and Development",
    subTitle: "Cheeseologists at Work",
    copy: "Our team of dedicated cheeseologists work tirelessly to perfect the science of cheese-infused toothbrushes. They combine their expertise in dentistry and fromage to create the ultimate dental delicacy.",
    imgPrompt:
      "A laboratory setting with scientists wearing lab coats and holding toothbrushes dipped in cheese",
    img: "/imgs/secondhandToothbrushes-7.png",
    imgName: "secondhandToothbrushes-7",
  },
  {
    slideNumber: 8,
    title: "Cheese-Flavored Floss",
    subTitle: "Completing the Dairy Dental Regimen",
    copy: "Take your cheese dental experience to the next level with our cheese-flavored floss! Seamlessly transition from brushing to flossing while keeping the delicious cheesiness intact.",
    imgPrompt: "A spool of floss made out of cheese",
    img: "/imgs/secondhandToothbrushes-8.png",
    imgName: "secondhandToothbrushes-8",
  },
  {
    slideNumber: 9,
    title: "Frequently Asked Questions",
    subTitle: "Because You're Curious",
    copy: "Q: Is the cheese flavor organic? A: Absolutely! We only use the finest organic cheese to ensure the most authentic experience. Q: Can I still use toothpaste? A: While not necessary, using cheese-flavored toothpaste amplifies the taste sensation!",
    imgPrompt: "A comic-style thought bubble with question marks",
    img: "/imgs/secondhandToothbrushes-9.png",
    imgName: "secondhandToothbrushes-9",
  },
  {
    slideNumber: 10,
    title: "Cheese Power for Your Smile",
    subTitle: "Unleash the Cheesy Grin",
    copy: "With our innovative cheese-flavored secondhand toothbrushes, you'll never look at oral hygiene the same way again. Embrace the weirdness and enjoy a smile that's a cut above the rest!",
    imgPrompt: "A person with a huge, exaggerated smile made of cheese",
    img: "/imgs/secondhandToothbrushes-10.png",
    imgName: "secondhandToothbrushes-10",
  },
];
